/****************************************************************************
 * @file      ec_group.hpp
 * @brief     Elliptic Curve Cryptography (ECC) abstractions for Taihang.
 * @details   Defines ECGroup and ECPoint using the Context-Instance pattern,
 * including highly optimized vectorized arithmetic and MSM.
 * @author    This file is part of Taihang, developed by Yu Chen.
 *****************************************************************************/

#ifndef TAIHANG_CRYPTO_EC_GROUP_HPP
#define TAIHANG_CRYPTO_EC_GROUP_HPP

#include <string>
#include <vector>
#include <iostream>
#include <taihang/crypto/bigint.hpp>
#include <taihang/crypto/zn.hpp>
#include <taihang/crypto/bn_ctx.hpp>
#include <taihang/crypto/block.hpp>
#include <taihang/crypto/aes.hpp>
#include <taihang/crypto/crypto_hash.hpp>
#include <taihang/common/config.hpp>
#include <taihang/common/check.hpp>

// Opaque forward declarations for OpenSSL structures
using EC_GROUP = struct ec_group_st;
using EC_POINT = struct ec_point_st;

namespace taihang {

class ECPoint; 

/**
 * @class ECGroup
 * @brief Context class managing Elliptic Curve group parameters (The Context).
 * @details Acts as a factory for ECPoint instances and manages the OpenSSL lifecycle.
 * Contains precomputed tables and curve parameters for efficient math.
 */
class ECGroup {
public:
    // --- Members (Public) ---
    EC_GROUP* group_ptr; // Raw OpenSSL handle to the internal group structure.
    const EC_POINT* generator; // Constant pointer to the group's base point (generator G). 
    
    int curve_id = 0; 

    BigInt order; // The number of points in the subgroup generated by G (The Order n).
    BigInt cofactor; // h = #E(K)/n: The ratio between the total point count and the subgroup order. 
    BigInt p; // The prime characteristic of the underlying finite field GF(p). 
    BigInt a; // The 'a' coefficient in the curve equation: y^2 = x^3 + ax + b. 
    BigInt b; // The 'b' coefficient in the curve equation: y^2 = x^3 + ax + b. 

    size_t base_field_byte_len; // The length of the prime p in bytes (e.g., 32 for a 256-bit curve). 
    size_t point_byte_len; // The length of an uncompressed serialized point in bytes. 
    size_t point_byte_compressed_len; // The length of a compressed serialized point in bytes. 

    // --- Lifecycle ---

    /** @brief Returns the global singleton instance (default is Secp256r1). */
    static const ECGroup& get_default_group();

    /** * @brief Constructs an EC group context.
     * @param curve_id The NID of the curve (OpenSSL naming).
     * @param precompute_flag Whether to precompute the multiplication table.
     */
    // prime256v1 (OpenSSL name) secp256r1 ANSI X9.62 prime256v1
    explicit ECGroup(int curve_id = 415, bool precompute_flag = true); 
    ~ECGroup();

    // Disable copying to maintain pointer stability for ECPoint instances
    ECGroup(const ECGroup&) = delete;
    ECGroup& operator=(const ECGroup&) = delete;

    // --- Factory Methods ---

    /** @brief Creates a point at infinity (The identity element 0). */
    ECPoint get_infinity() const;

    /**  @brief Creates a deep copy of the generator point G. */
    ECPoint get_generator() const;
    
    /** @brief Generates a cryptographically random point on the curve. */
    ECPoint gen_random() const;

    /** * @brief Generates a vector of random points. 
     * @param n The number of points to generate.
     */
    std::vector<ECPoint> gen_random(size_t n) const;

    // --- Status and Optimization ---
    
    /** @brief Computes fixed-point multiplication tables for performance. */
    void precompute() const;

    /** @brief Checks if precomputation has been successfully performed. */
    bool is_precomputed() const;

    // NEW: Returns the Zn context representing the scalar field (mod n)
    // Note: Returns by value (lightweight context)
    Zn get_scalar_field() const {
        return Zn(this->order);
    }
};

/**
 * @class ECPoint
 * @brief High-level C++ wrapper for an Elliptic Curve point (The Instance).
 */
class ECPoint {
public:
    // --- Members (Public) ---
    const ECGroup* group_ctx; // Pointer to the parent ECGroup context. 
    EC_POINT* pt_ptr; // Raw OpenSSL handle to the internal point structure. 

    // --- Lifecycle ---
    explicit ECPoint(const ECGroup* group = &ECGroup::get_default_group());
    explicit ECPoint(const ECGroup& group) : ECPoint(&group) {} 
    
    ECPoint(std::shared_ptr<ECGroup> group) : ECPoint(group.get()) {} 
    ECPoint(const ECPoint& other);
    ECPoint(ECPoint&& other) noexcept;
    ~ECPoint();

    ECPoint& operator=(const ECPoint& other);
    ECPoint& operator=(ECPoint&& other) noexcept;

    // --- Core Arithmetic ---
    /** @brief Returns a new point resulting from point addition: (this + other). */
    ECPoint add(const ECPoint& other) const;

    // --- In-place Operations (avoids temporary ECPoint allocation) ---
    /**
     * @brief Adds other to this point in-place.
     * @details Writes result directly into this->pt_ptr, avoiding EC_POINT_new/free.
     *          Use in hot loops instead of operator+ to eliminate heap allocation overhead.
     */
    void add_inplace(const ECPoint& other);

    /** @brief Returns a new point resulting from point subtraction: (this - other). */
    ECPoint sub(const ECPoint& other) const;

    /** @brief Returns a new point resulting from scalar multiplication: (scalar * this). */
    ECPoint mul(const BigInt& scalar) const;
    // optimized for generator
    ECPoint mul_generator(const BigInt& scalar) const;

    /** @brief Returns a new point resulting from scalar multiplication: (scalar * this). */
    ECPoint mul(const ZnElement& scalar) const;
    // optimized for generator
    ECPoint mul_generator(const ZnElement& scalar) const;

    /** @brief Returns the additive inverse of this point (-P). */
    ECPoint neg() const;

    ECPoint dbl() const; // Added explicit double for completeness

    // --- Utility and Validation ---

    /** @brief Sets the point to the identity element (infinity). */
    void set_infinity();

    /** @brief Returns true if the point is at infinity. */
    bool is_at_infinity() const;

    /** @brief Returns true if the point lies on the parent group's curve. */
    bool is_on_curve() const;

    /** @brief Compares two points for equality. */
    bool compare_to(const ECPoint& other) const;

    // --- hash to integer ---
    /** High-performance hash of the point.
     * @details Uses AES-NI hardware intrinsics to map the point to 64 bits.
     *          Optimized for hash table keys (e.g., BSGS).
     */
    uint64_t aeshash_to_uint64() const;

    // use xxHash3: gold standard for non-cryptographic hashing, significantly faster than MurmurHash2/3.
    // avoid heavy serialization EC_POINT_point2oct: Use EC_POINT_get_affine_coordinates to get the raw $X$ coordinate.
    uint64_t xxhash_to_uint64() const;

    // --- Serialization ---

    /** 
     * @brief Serializes the point to a fixed-length byte array.
     * @details Writes to the provided buffer. 
     *          The buffer MUST be large enough (check group->point_byte_len).
     *          Infinity is written as all zeros.
     */
    void to_bytes(uint8_t* buffer) const;

    /** 
     * @brief Convenience wrapper for to_bytes(buffer).
     * @return A vector of fixed size.
     */
    std::vector<uint8_t> to_bytes() const;

    /** 
     * @brief Deserializes from a fixed-length byte array.
     * @details The length is determined implicitly by the group's configuration.
     */
    void from_bytes(const uint8_t* buffer);
    void from_bytes(const std::vector<uint8_t> input); 


    // --- debugging ---
    std::string to_hex() const; 
    void print(std::string_view label, std::ostream& os) const; 

    // --- Operator Overloads ---

    inline ECPoint operator+(const ECPoint& other) const { return add(other); }
    inline ECPoint operator-(const ECPoint& other) const { return sub(other); }

    inline ECPoint operator*(const BigInt& scalar) const { return mul(scalar); }
    inline ECPoint operator*(const ZnElement& scalar) const { return mul(scalar); }

    inline ECPoint operator-() const { return neg(); }
    inline bool operator==(const ECPoint& other) const { return compare_to(other); }
    inline bool operator!=(const ECPoint& other) const { return !compare_to(other); }

    /** @brief Stream output operator for de-serialization. */
    friend std::ostream& operator<<(std::ostream& os, const ECPoint& point);

    /** @brief Stream input operator for serialization. */
    friend std::istream& operator>>(std::istream& is, ECPoint& point);
};

// --- Vectorized & Parallel Operations ---

/** * @brief Multi-Scalar Multiplication: sum(vec_A[i] * vec_a[i]). 
 * @details Uses OpenSSL simultaneous multiplication for maximum efficiency.
 */
ECPoint ec_point_msm(const std::vector<ECPoint>& vec_A, const std::vector<BigInt>& vec_a);
ECPoint ec_point_msm(const std::vector<ECPoint>& vec_A, const std::vector<ZnElement>& vec_a);

/** * @brief MSM on a specific sub-range of vectors. 
 * @param start_index The inclusive starting index.
 * @param end_index The exclusive ending index.
 */
ECPoint ec_point_msm(const std::vector<ECPoint>& vec_A, const std::vector<BigInt>& vec_a, size_t start_index, size_t end_index);
ECPoint ec_point_msm(const std::vector<ECPoint>& vec_A, const std::vector<ZnElement>& vec_a, size_t start_index, size_t end_index);

/** * @brief Parallel element-wise addition: result[i] = vec_A[i] + vec_B[i]. 
 * @details Parallelized using OpenMP based on config::thread_num.
 */
std::vector<ECPoint> ec_point_vector_add(const std::vector<ECPoint>& vec_A, const std::vector<ECPoint>& vec_B);

/** * @brief Parallel scalar multiplication: result[i] = vec_A[i] * a. 
 * @details Every point in the vector is multiplied by the same single scalar.
 */
std::vector<ECPoint> ec_point_vector_mul(const std::vector<ECPoint>& vec_A, const BigInt& a);
std::vector<ECPoint> ec_point_vector_mul(const std::vector<ECPoint>& vec_A, const ZnElement& a);

/** * @brief Parallel element-wise scalar multiplication: result[i] = vec_A[i] * vec_a[i]. 
 * @details Every point is multiplied by its corresponding scalar in the weight vector.
 */
std::vector<ECPoint> ec_point_vector_mul(const std::vector<ECPoint>& vec_A, const std::vector<BigInt>& vec_a);
std::vector<ECPoint> ec_point_vector_mul(const std::vector<ECPoint>& vec_A, const std::vector<ZnElement>& vec_a);


// --- Fast Hashing (Try-and-Increment with AES-NI) ---

/** @brief Fast mapping for raw bytes. Uses SHA256 then AES-NI. */
ECPoint hash_to_curve_fast(const uint8_t* data, size_t len, const ECGroup& group = ECGroup::get_default_group());
/** @brief Fast mapping for strings. */
ECPoint hash_to_curve_fast(const std::string& data, const ECGroup& group = ECGroup::get_default_group());
/** @brief Fast mapping for 128-bit blocks. */
ECPoint hash_to_curve_fast(const Block& data, const ECGroup& group = ECGroup::get_default_group());


// --- Standard Hashing (IETF RFC 9380 / SSWU) ---

/** @brief RFC 9380 compliant mapping for raw bytes. Requires a DST. */
ECPoint hash_to_curve_standard(const uint8_t* data, size_t len, const std::string& dst, const ECGroup& group = ECGroup::get_default_group());
/** @brief RFC 9380 compliant mapping for strings. */
ECPoint hash_to_curve_standard(const std::string& data, const std::string& dst, const ECGroup& group = ECGroup::get_default_group());
/** @brief RFC 9380 compliant mapping for 128-bit blocks. */
ECPoint hash_to_curve_standard(const Block& data, const std::string& dst, const ECGroup& group = ECGroup::get_default_group());

} // namespace taihang

#endif // TAIHANG_CRYPTO_EC_GROUP_HPP





